#ifndef MARKANDSWEEP_CONSTANTS_H
#define MARKANDSWEEP_CONSTANTS_H

#define WORD_SIZE 8

#define BLOCK_SIZE_BITS 9
#define BLOCK_SIZE (1 << BLOCK_SIZE_BITS)

#define BLOCK_MASK (~((unsigned long long)(BLOCK_SIZE * WORD_SIZE) - 1))


#define OBJECT_MIN_SIZE_BITS 1
#define OBJECT_MIN_SIZE (1 << OBJECT_MIN_SIZE_BITS)

#define LARGE_OBJECT_MIN_SIZE_BITS 7
#define LARGE_OBJECT_MIN_SIZE (1 << LARGE_OBJECT_MIN_SIZE_BITS)

#define LARGE_OBJECT_MIN_SIZE_MASK (~((unsigned long long)(LARGE_OBJECT_MIN_SIZE * WORD_SIZE) - 1))

#define LARGE_OBJECT_MAX_SIZE_BITS 31
#define LARGE_OBJECT_MAX_SIZE (1UL << LARGE_OBJECT_MAX_SIZE_BITS)


#endif //MARKANDSWEEP_CONSTANTS_H
